### ISSUE TITLE
Constructing URLs in emails

### ISSUE THREAD

**Issue by jsonmaur** [batteries-included/batteries-included#1018]
The email URLs are constructed using `Phoenix.VerifiedRoutes.url/1` as well as `config :home_base_web, :home_url`. This results in links with `127.0.0.1` in development and testing. In production, there is a config value to change `home_url` to use `batteriesincl.com`, but we need a similar config value in prod for `config :home_base_web, HomeBaseWeb.Endpoint, url: [host: "app.batteriesincl.com"]` (depending on what subdomain we're gonna host home base on).

@elliottneilclark @JTarasovic Will this mess anything up with the production hosting? I can try to come up with a better way to construct those URLs if so.

**Comment by elliottneilclark** [comment]
Can't we use the [`HomeWeb.RequestUrl` ](https://github.com/batteries-included/batteries-included/blob/669c89118717fa02acdac41ed877481072dd116f/platform_umbrella/apps/home_base_web/lib/home_base_web/request_host.ex#L1)to get the host for sending these?  That gets you hostname and port and SSL or not on every request. That should allow us to know the base URL.

Using the current host is my preferred way since it works on testing too. If that doesn't work, then the config should default to our production host currently and take an environment variable as an override. That will likely need to be handled in config/production.ex or `apps/home_base_web/config/runtime.exs`

**Comment by jsonmaur** [comment]
Yeah I did not know that module existed 🙃 That should work.
